# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('jamming', ['spectrum', 'mmwave'])
    module.source = [
        'model/mmwave-jamming-model.cc',
        'helper/jamming-model-helper.cc'
        ]

    headers = bld(features='ns3header')
    headers.module = 'jamming'
    headers.source = [
        'model/mmwave-jamming-model.h',
        'helper/jamming-model-helper.h'
        ]


    # bld.ns3_python_bindings()
    module_test = bld.create_ns3_module_test_library('spectrum')

    module_test.source = [
        'test/simple-jamming-test.cc'
        ]
